### ISSUE TITLE
Mass movement?

### ISSUE THREAD

**Issue by dwonderley** [dwonderley/mookAI#10]
A user requested the ability to move multiple tokens at once, whether that be "all NPCs up until the next PC turn" or "all NPCs on the current initiative."

**Comment by dwonderley** [comment]
This is dangerous behavior without a faction system because it could turn friendly NPCs hostile, but those turns can always be rejected

**Comment by dwonderley** [comment]
Likely, this feature will use an alternate keybind, like shift+g or ctrl+g

**Comment by brunocalado** [comment]
This will be so cool.

You could simulate a war!

**Comment by dwonderley** [comment]
Implemented with shift + g. This combination moves all selected tokens, even if they aren't in the combat tracker.
