### ISSUE TITLE
Feature request: trigger AI when token(s) are selected but not in the combat tracker

### ISSUE THREAD

**Issue by caewok** [dwonderley/mookAI#12]
Use case: If you have a lot of creatures, say, 50 kobolds, you might not want to put each one in the combat tracker. Instead, you might split them into groups of 10 and put 5 temporary combatants in the combat tracker, one for each "squad." But as far as I can tell, MookAI only runs for the current combatant in the tracker. 

Instead, I would like the option of selecting one or more combatants (for example, selecting the 10 kobolds in their "squad") and hitting the "g" key to trigger MookAI for each, regardless of whether they are in the tracker. Thanks!

**Comment by dwonderley** [comment]
Implemented with shift+g. See issue 10.
shift+g moves all selected tokens. I'll probably try to support saving groups at some point, but I haven't decided on what that interface should be.
