### ISSUE TITLE
"Perfect Vision" integration?

### ISSUE THREAD

**Issue by NukeMaster0** [dwonderley/mookAI#15]
This module called "Perfect Vision" has a feature where entities can hide in the shadows (Automatically) and if someone has vision they can't see anything in the dark and must rely on the light, this could be cool for an ambush or something. The issue is when the A.I. (Foundry Patrol) somehow finds the players even though they are hidden in the dark, not sure if you could do anything about it, but worth a try! Thank you!

What the player sees:
![image](https://user-images.githubusercontent.com/68701755/103018297-ffe72b80-4512-11eb-8dc4-29ee437e86fc.png)

What the A.I. sees:
![image](https://user-images.githubusercontent.com/68701755/103018311-04abdf80-4513-11eb-987c-32d333c715dd.png)

**Comment by dwonderley** [comment]
I can take a look at the module code and see how it manages vision. As a general rule, I can't support all modules that alter FVTT functionality. In this instance, it's a module that it makes sense for me to support, but I expect that there are some significant technical challenges. Still, I'll see what I can do.

**Comment by dwonderley** [comment]
I looked into it a bit, and to determine sight, I'm making a direct call to the FVTT API:
`	canSee (id_)
	{
		// I have no idea how this works, but it seems to anyway
		return canvas.tokens.children[0].children.some (e =>
			{ return e.id === id_ && e.isVisible; });
	}
`
It seems that the changes the other module developer is making aren't updating this value. I'll see if I can contact them and if we can work out what is going wrong.

**Comment by NukeMaster0** [comment]
Thank you!

**Comment by dev7355608** [comment]
@NukeMaster0 
> This module called "Perfect Vision" has a feature where entities can hide in the shadows (Automatically) [...]

Not sure what you mean by that. Could you elaborate?

**Comment by dev7355608** [comment]
@NukeMaster0 Is this still an issue? It has been a couple of Perfect Vision releases since you reported this issue.

**Comment by CalabC** [comment]
> @NukeMaster0 Is this still an issue? It has been a couple of Perfect Vision releases since you reported this issue.

Sorry for the long wait, it works amazing and here's proof, thank you! (This can now be closed!)



https://user-images.githubusercontent.com/76928388/103583124-2c089200-4ead-11eb-93d2-74b6c2a6e1f2.mp4

**Comment by NukeMaster0** [comment]
Sorry about that, CalabC is my alt account when I'm away from home.
