### ISSUE TITLE
Not making attack rolls

### ISSUE THREAD

**Issue by Avitale34** [dwonderley/mookAI#2]
Wow this module is amazing!!! Its the targeting and movement is working great for me but it is not rolling attacks for some reason.

**Comment by Avitale34** [comment]
Edit: seems to be an incompatibility with MIDI QOL

**Comment by dwonderley** [comment]
I thought I had midi-qol working at some point. I'm probably not up to date. Let me look into it...

**Comment by dwonderley** [comment]
I remember now. I disabled it when 0.7.5 hit because a few of its dependencies hadn't updated yet. I assume that, since you're using it, that isn't a problem any more. I'll update and correct the compatability issue.

**Comment by dwonderley** [comment]
From midi-qol documentation:
"Better Rolls If you are using BetterRolls (which is a great module), midi-qol takes over once the hit/damage card is placed by better rolls. This means that resource consumption, template placement and critical/fumble determination is all handled by BetterRolls before midi-qol kicks in. Midi-qol checks hits, saves, applies damage and calls active effects."

I believe this means I need to invoke better rolls directly, if it is enabled, so I will remove the check for midi/minor-qol, and I have tested that damage will be rolled correctly this way with each module combination.

**Comment by Avitale34** [comment]
Thank you for looking into that! I do not have Better Rolls installed just MidiQOL! Look forward to using this great mod!

**Comment by dwonderley** [comment]
The fix should be live now. I'm verifying it now. I'm sorry it took so long; I'm new to git and finding it absolutely awful compared to other version controls I've used.

**Comment by Avitale34** [comment]
I don't think foundry has the updated version yet. I just uninstalled and reinstalled and its still 0.0.1. Appreciate the swiftness of your response!

**Comment by Avitale34** [comment]
Works great now! Can I put in a feature request to apply "multiattacks" not sure if that's even possible.
