### ISSUE TITLE
Please add an option to not rotate tokens as they path.

### ISSUE THREAD

**Issue by GvosRamsey** [dwonderley/mookAI#3]

**Comment by dwonderley** [comment]
Someone else requested this, and I looked into it, but it is slightly more complicated than it sounds. Token vision is determined by which way the token is facing, so if the token doesn't rotate, it can't see what it is supposed to when its vision cone is reduced. I'm looking into it.

**Comment by troygoode** [comment]
@dwonderley isn't that only the case if the token's sight angle isn't `360`? perhaps have this optional setting only do this when that is also true

**Comment by DeadlyArtist** [comment]
why is that dependant on the vision cone anyways? in DnD at least vision is not defined by a cone but rather a sphere. since rn your module is dnd dependent, vision depending on a cone would rather be opt in than opt out unless i missed something here.

**Comment by dwonderley** [comment]
Implemented

**Comment by DFreds** [comment]
Tokens appear to still be rotating, even though I tried disabling it in the settings.
