### ISSUE TITLE
Mooktype==undefined  causing 'Failed to select a target'

### ISSUE THREAD

**Issue by Kreals** [dwonderley/mookAI#4]
Nice module, unfortunatly when i first tried to use it in my existing campaign there was no joy. I kept getting the following error.

```
Failed to select a target
takeTurn @ mookAI.js:353
async function (async)
takeTurn @ mookAI.js:338
(anonymous) @ mookAI.js:212
```

I traced it down to the fact that mook_.mookModel.settings.mookType doesnt seem to be set by default. I understand selecting mooktype is not yet possible by the GUI but might be worth looking at the mook class initialisation process and/or temporarily assigning one of EAGER_BEAVER, NELSON, SHIA, VEGETA as the mookType in the chooseTarget method of the behaviour class until you have time to fix it properly (as I have done). 

Again, nice module. My work typically involves AI, computer vision etc so if you ever want help with decision making algorithms etc perhaps i can contribute at a later date.

**Comment by Varriount** [comment]
@Kreals It appears that there is a way to adjust the AI setting, however the error happens when the user hasn't adjusted the setting previously (for instance, when the module is first installed and activated).

**Comment by dwonderley** [comment]
Thanks for the bug report and for the assist Varriount! It's interesting that you're having this problem; it has a default value set when the setting is registered. I'll look into this some more and put up a fix as soon as I can. 

I'm open to collaboration. I'm part of the ai workgroup in the "League of Extraordinary FoundryVTT Developers" discord server.  That's probably the best place to discuss development. If that appeals to you, the server is open invite. You can get a link from the regular fvtt discord.

**Comment by dwonderley** [comment]
Also, to clarify, you _can_ change the mook type, but it's a global setting right now.

**Comment by dwonderley** [comment]
I've added a default value and a check when the mookType is used, so this shouldn't be a problem any more. I should have done that to being with, but it's still concerning that the default value isn't being registered properly.
