### ISSUE TITLE
optionally default or fix null/0 move speed

### ISSUE THREAD

**Issue by troygoode** [dwonderley/mookAI#7]
Some of the creatures I'm using were unfortunately imported with null walk speeds from D&D Beyond from VTTA. Attempting to use mook with these creatures fails silently (console error `Invalid Path initialization: bad search range`). It'd be nice to have an option to easily fix this. Two possible recommendations here:

* Module setting to default to `30 feet` if the walk speed is null / undefined / 0
* Or prompt the DM when they attempt to use mook on a creature with null/undefined/0 walk speed with a dialog window. Even better, let the DM click a button to immediately fix the creature so they can try again

**Comment by dwonderley** [comment]
In a recent update to the 5e system, the movement speed stat was, uh, moved to a different spot. mookAI was looking at a deprecated field, and that's probably what's causing your problem. I pushed a fix for that earlier today, so you might want to check if you're up to date.

If that doesn't address your issue, I'm planning to add customization to the dialog window in a future update. Move speed will be one of the fields.

You're right that it shouldn't fail silently. I was planning to set a default value of 30, but looking at the code again, it seems I didn't. I'll put that in the next patch.

**Comment by troygoode** [comment]
I was on the latest version of mookAI; the problem was definitely that my NPC had a null movement speed set on their sheet (which isn't mookAI's fault, obviosuly). I think just setting it to a default of 30 is a sane fallback - thanks!

**Comment by dwonderley** [comment]
I agree! I've pushed the fix.
