### ISSUE TITLE
option to move but not attack

### ISSUE THREAD

**Issue by troygoode** [dwonderley/mookAI#8]
It'd be great if we could use a different shortcut (`shift+G`?) to have mook move and target, but not roll the attack / end the turn. This would be helpful if the creature has multi-attack, for instance.

**Comment by dwonderley** [comment]
I could add that, sure.

mookAI supports multi-attack, but the user interface for it hasn't been built yet. I'm planning to put it in the confirmation dialog screen.

**Comment by troygoode** [comment]
The more I think about it, my personal preference here would be an option to just completely turn off mook automatically moving to the next turn. I can already do that very easily with mook's `n` shortcut key! That makes it easy for me to hit `g` followed by `n` if it is a simple turn or I can do some stuff between the `g` and the `n` if I want (such as describing the attack before it is officially the next person/creature's turn).

**Comment by dwonderley** [comment]
I missed this comment. I can add a setting for that in the release tomorrow.
