### ISSUE TITLE
not taking turn for player character

### ISSUE THREAD

**Issue by DeadlyArtist** [dwonderley/mookAI#9]
Whenever I try to activate the module, it doesn't do anything. Then, I realized (saw info in console) it doesn't do anything for player owned characters. This is a very big problem for the very campaign I downloaded this module for. In this campaign, the players can move the monsters as well, so everyone is the owner of every monster. Might be an edge case, but allow for a setting to allow the ai to overtake player controlled non player character tokens. I looked into the code and saw it would be pretty easy to implement as well. Thanks for your consideration.

**Comment by dwonderley** [comment]
I'm not sure there's an easy way to determine if a token is an NPC other than by checking if they are owned by a player.
However, this check predates the confirmation screen, and I'm not sure it's needed any more. If I add a warning to that dialog, then the GM can reject a PC plan if they want to. This would allow GMs to have more balanced "mind control" effects, for example.
I'm still thinking about this, but I'm leaning toward adding this warning into the patch that adds functionality to the confirmation dialog.

**Comment by dwonderley** [comment]
I have added it
